### ISSUE TITLE
PyPI package doesn't work

### ISSUE THREAD

**Issue by lukecyca** [dvc94ch/pykicad#3]
Thank you for this project!

When installing with `pip install pykicad` I get this error:
```
Collecting pykicad
  Downloading pykicad-0.0.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/3s/j1dvrg5j2815ndvqnzh1x59r0000gn/T/pip-build-EBmDiK/pykicad/setup.py", line 8, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/var/folders/3s/j1dvrg5j2815ndvqnzh1x59r0000gn/T/pip-build-EBmDiK/pykicad/setup.py", line 8, in <module>

        long_description=open('README.md').read(),

    IOError: [Errno 2] No such file or directory: 'README.md'
```

This is because `setup.py` is trying to read the `README.md` file, but it isn't included in the dist tarball. To include it, I think you need to use the [package_data](http://peak.telecommunity.com/DevCenter/setuptools#including-data-files) arguments.

**Comment by dvc94ch** [comment]
Fixed! Thanks for reporting it. v0.0.2 should also fix the startup time (5s to import the module...).
